// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddnewownerwithwrongformatTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void addnewownerwithwrongformat() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1920, 1040);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) span:nth-child(2)")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Анатолий");
    driver.FindElement(By.Id("lastName")).SendKeys("Кияшенко");
    driver.FindElement(By.Id("address")).SendKeys("Князей Острожских 1, 166");
    driver.FindElement(By.Id("city")).SendKeys("Житомир");
    driver.FindElement(By.Id("telephone")).SendKeys("0675060694");
    driver.FindElement(By.Id("telephone")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(6)")).Click();
    driver.FindElement(By.Id("telephone")).SendKeys("dfgfgjhghj");
    driver.FindElement(By.CssSelector(".col-sm-offset-2")).Click();
    driver.FindElement(By.Id("telephone")).Click();
    driver.FindElement(By.Id("telephone")).SendKeys("df43434");
    driver.FindElement(By.CssSelector(".col-sm-offset-2")).Click();
    driver.FindElement(By.CssSelector(".has-error")).Click();
    driver.FindElement(By.CssSelector(".has-error")).Click();
    driver.FindElement(By.CssSelector(".has-error")).Click();
    driver.FindElement(By.Id("telephone")).SendKeys("####");
    driver.FindElement(By.CssSelector(".col-sm-offset-2")).Click();
    driver.FindElement(By.CssSelector(".has-error")).Click();
    driver.FindElement(By.Id("telephone")).SendKeys(" ");
    driver.FindElement(By.CssSelector(".col-sm-offset-2")).Click();
  }
}
