// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestaddnewvisitformvalidationTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testaddnewvisitformvalidation() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1920, 1040);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".open li:nth-child(1) > a"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.Close();
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.CssSelector(".petOwner:nth-child(467) a")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.CssSelector(".addNewVisit")).Click();
    {
      var element = driver.FindElement(By.CssSelector("path"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector("path")).Click();
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".mat-calendar-body-today")).Click();
    driver.FindElement(By.CssSelector(".addVisit")).Click();
    driver.FindElement(By.Id("description")).Click();
    driver.FindElement(By.Id("description")).SendKeys("yyjkjlkl");
    driver.FindElement(By.Name("date")).Click();
    driver.FindElement(By.Name("date")).SendKeys("2021/11/31");
    driver.FindElement(By.CssSelector(".addVisit")).Click();
    driver.FindElement(By.Name("date")).Click();
    driver.FindElement(By.Name("date")).SendKeys("2021/11/30");
    driver.FindElement(By.CssSelector(".addVisit")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".addVisit"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
  }
}
